MovieProject/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using Models.EF;
using PagedList.Mvc;
using PagedList;
using Models.Dao;
using System.Web.ModelBinding;


namespace MovieProject.Areas.Admin.Controllers
{
    public class CategoryController : BaseController
    {
        // GET: Admin/Category
        MovieProjectDbcontext db = new MovieProjectDbcontext();
        [HashCredential(RoleID = "VIEW_USER")]
        public ActionResult Index(int page = 1, int pageSize = 10)
        {


            var dao = new CategoryDao();
            var model = dao.ListPg(page, pageSize);
            return View(model);
        }

        public ActionResult getList(int id)
        {
            JsonSerializerSettings jss = new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore };
            var hs = db.Categories.SingleOrDefault(x => x.CategoryID == id);
            var result = JsonConvert.SerializeObject(hs, Formatting.Indented, jss);
            return this.Json(result, JsonRequestBehavior.AllowGet);
        }
        [HashCredential(RoleID = "EDIT_USER")]
        [HashCredential(RoleID = "ADD_USER")]
        public ActionResult Add(Category model, string submit)
        {
            if (submit == "Thêm")
            {
                if (model != null)
                {
                    model.NameCategory = model.NameCategory.ToString();
                    model.CreatedDate = model.CreatedDate.GetValueOrDefault(System.DateTime.Now);
                    model.Status = model.Status;
                    db.Categories.Add(model);
                    db.SaveChanges();
                    model = null;
                }
                SetAlert("Thêm thể loại thành công", "success");
                return RedirectToAction("Index");
            }
            else if (submit == "Cập Nhật")
            {
                if (model != null)
                {
                    var list = db.Categories.SingleOrDefault(x => x.CategoryID == model.CategoryID);
                    list.NameCategory = model.NameCategory;
                    list.CreatedDate = model.CreatedDate.GetValueOrDefault(System.DateTime.Now);
                    list.Status = model.Status;
                    db.SaveChanges();
                    model = null;
                }
                SetAlert("Sửa thể loại thành công", "success");
                return RedirectToAction("Index");
            }
            else if (submit == "Tìm")
            {
                if (!string.IsNullOrEmpty(model.NameCategory))
                {
                    List<Category> list = GetData().Where(s => s.NameCategory.Contains(model.NameCategory)).
                        ToList();
                    return View("Index", list);
                }
                else
                {
                    List<Category> list = GetData();
                    return View("Index", list);
                }
            }
            else
            {
                List<Category> list = GetData().OrderBy(s => s.NameCategory).ToList();
                return View("Index", list);
            }
        }
        public List<Category> GetData()
        {
            return db.Categories.ToList();


        }
        public ActionResult Delete(int id)
        {
            new CategoryDao().Delete(id);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public JsonResult ChangeStatus(int id)
        {
            var result = new CategoryDao().ChangeStatus(id);
            return Json(new
            {
                status = result

            });
        }



    }
}

MovieProject/Controllers/MController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models.Dao;
using PagedList;
using Models.EF;
using System.Data.Entity;

namespace MovieProject.Controllers
{
    public class MController : Controller
    {
        // GET: Movie
        MovieProjectDbcontext db = new MovieProjectDbcontext();
        public ActionResult Index()
        {

            return View();
        }
        [ChildActionOnly]

        public PartialViewResult Category()
        {
            var model = new CategoryDao().ListAll();
            return PartialView(model);

        }
        [ChildActionOnly]

        public PartialViewResult Country()
        {
            var model = new CountryDao().ListAll();
            return PartialView(model);

        }
        [ChildActionOnly]

        public PartialViewResult MenuBottom()
        {
            var model = new CategoryDao().ListAll();
            return PartialView(model);
        }

        public ActionResult Search()
        {

            return View();
        }

        public ActionResult CategoryPage(long idcate, int page = 1)
        {
            var moviDao = new MovieDao();
            var cate = new CategoryDao().ViewDetail(idcate);
            ViewBag.cate = cate;
            ViewBag.ListMovieNew = moviDao.ListMovieNew(12);
            var model = moviDao.ListByCateId(idcate);
            return View(model.ToPagedList(page, 12));
        }
        public ActionResult CountryPage(long idc, int page = 1)
        {
            var movieDao = new MovieDao();
            var country = new CountryDao().ViewDetail(idc);
            ViewBag.country = country;
            ViewBag.ListMovieNew = movieDao.ListMovieNew(12);
            var model = movieDao.ListByCountryID(idc);
            return View(model.ToPagedList(page, 12));

        }
        public ActionResult MovieDetail(int id)
        {

            var movie = new MovieDao().ViewDetail(id);
            ViewBag.movie = movie;
            ViewBag.category = new CategoryDao().ViewDetail(movie.CategoryID.Value);
            ViewBag.ListMovieRelated = new MovieDao().ListMovieRelated(id, 7);
            ViewBag.ListMovieNew1 = new MovieDao().ListMovieNew1(12);
            Movie upview = db.Movies.Find(id);
            if (upview.Viewed == null)
            {
                upview.Viewed = 1;
                upview.Name = upview.Name;
                upview.Image = upview.Image;
                upview.MoreImages = upview.MoreImages;
                upview.Actor = upview.Actor;
                upview.Description = upview.Description;
                upview.Directors = upview.Directors;
                upview.Time = upview.Time;
                upview.Year = upview.Year;
                upview.Country = upview.Country;
                upview.MovieLink = upview.MovieLink;
                upview.TrailerLink = upview.TrailerLink;
                upview.CategoryID = upview.CategoryID;
                upview.Rate = upview.Rate;
                upview.CreatedDate = upview.CreatedDate;
                upview.Status = upview.Status;
                upview.TopHot = upview.TopHot;
                db.Entry(upview).State = EntityState.Modified;
                db.SaveChanges();
                return View(upview);
            }
            else
            {
                upview.Viewed = upview.Viewed + 1;
                upview.Name = upview.Name;
                upview.Image = upview.Image;
                upview.MoreImages = upview.MoreImages;
                upview.Actor = upview.Actor;
                upview.Description = upview.Description;
                upview.Directors = upview.Directors;
                upview.Time = upview.Time;
                upview.Year = upview.Year;
                upview.Country = upview.Country;
                upview.MovieLink = upview.MovieLink;
                upview.TrailerLink = upview.TrailerLink;
                upview.CategoryID = upview.CategoryID;
                upview.Rate = upview.Rate;
                upview.CreatedDate = upview.CreatedDate;
                upview.Status = upview.Status;
                upview.TopHot = upview.TopHot;
                db.Entry(upview).State = EntityState.Modified;
                db.SaveChanges();
                return View(upview);
            }

        }

    }
}

MovieProject/Controllers/UserTController.cs
using Models.Dao;
using Models.EF;
using MovieProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MovieProject.Common;
using BotDetect.Web.Mvc;
using Facebook;
using System.Configuration;
using Common;

namespace MovieProject.Controllers
{
    public class UserTController : Controller
    {
        private Uri RedirectUri
        {
            get
            {
                var uriBuilder = new UriBuilder(Request.Url);
                uriBuilder.Query = null;
                uriBuilder.Fragment = null;
                uriBuilder.Path = Url.Action("FacebookCallback");
                return uriBuilder.Uri;
            }
        }
        // GET: UserT
        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }
        public ActionResult LoginFacebook()
        {
            var fb = new FacebookClient();
            var loginUrl = fb.GetLoginUrl(new
            {
                client_id = ConfigurationManager.AppSettings["FbAppId"],
                client_secret = ConfigurationManager.AppSettings["FbAppSecret"],
                redirect_uri = RedirectUri.AbsoluteUri,
                response_type = "code",
                scope = "email",
            });

            return Redirect(loginUrl.AbsoluteUri);
        }
        public ActionResult FacebookCallback(string code)
        {
            var fb = new FacebookClient();
            dynamic result = fb.Post("oauth/access_token", new
            {
                client_id = ConfigurationManager.AppSettings["FbAppId"],
                client_secret = ConfigurationManager.AppSettings["FbAppSecret"],
                redirect_uri = RedirectUri.AbsoluteUri,
                code = code
            });


            var accessToken = result.access_token;
            if (!string.IsNullOrEmpty(accessToken))
            {
                fb.AccessToken = accessToken;
                // Get the user's information, like email, first name, middle name etc
                dynamic me = fb.Get("me?fields=first_name,middle_name,last_name,id,email");
                string email = me.email;
                string userName = me.email;
                string firstname = me.first_name;
                string middlename = me.middle_name;
                string lastname = me.last_name;

                var user = new User();
                user.Email = email;
                user.UserName = email;
                user.Status = true;
                user.Name = firstname + " " + middlename + " " + lastname;
                user.CreatedDate = DateTime.Now;
                var resultInsert = new UserDao().InsertForFacebook(user);
                if (resultInsert > 0)
                {
                    var userSession = new UserLogin();
                    userSession.UserName = user.UserName;
                    userSession.UserID = user.UserID;
                    Session.Add(CommonContants.USER_SESSION, userSession);
                }
            }
            return Redirect("/");
        }
        public ActionResult Logout()
        {
            Session[Common.CommonContants.USER_SESSION] = null;
            return Redirect("/");
        }
        [HttpPost]
        public ActionResult Login(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var dao = new UserDao();
                var result = dao.Login(model.UserName, Encryptor.MD5Hash(model.Password));
                if (result == 1)
                {
                    var user = dao.GetById(model.UserName);
                    var userSession = new UserLogin();
                    userSession.UserName = user.UserName;
                    userSession.UserID = user.UserID;
                    Session.Add(Common.CommonContants.USER_SESSION, userSession);
                    return Redirect("/");
                }
                else if (result == 0)
                {
                    ModelState.AddModelError("", "Tài khoản không tồn tại");
                }
                else if (result == -1)
                {
                    ModelState.AddModelError("", "Tài khoản đang bị khoá");
                }
                else if (result == -2)
                {
                    ModelState.AddModelError("", "Mật khẩu không đúng");
                }

                else
                {
                    ModelState.AddModelError("", "Đăng nhập không thành công!");
                }
            }
            return View(model);
        }
        [HttpPost]
        [CaptchaValidationActionFilter("CaptchaCode", "registerCapcha", "Xác nhận mã không đúng!")]
        public ActionResult Register(RegisterModel model)
        {
            if (ModelState.IsValid)
            {
                var dao = new UserDao();
                if (dao.CheckUserName(model.UserName))
                {
                    ModelState.AddModelError("", "Tên đăng nhập đã tồn tại");
                }
                else if (dao.CheckEmail(model.Email))
                {
                    ModelState.AddModelError("", "Email đã tồn tại");
                }
                else
                {
                    var user = new User();
                    user.Name = model.Name;
                    user.UserName = model.UserName;
                    user.Password = Encryptor.MD5Hash(model.Password);
                    user.GroupID = "MEMBER";
                    user.CreatedDate = DateTime.Now;
                    user.Status = true;
                    user.Phone = model.Phone;
                    user.Email = model.Email;
                    var result = dao.InsertUser(user);
                    if (result > 0)
                    {
                        ViewBag.Success = "Đăng ký thành công ";
                        model = new RegisterModel();
                    }
                    else
                    {
                        ModelState.AddModelError("", "Đăng ký không thành công");
                    }


                }
            }
            return View(model);
        }
        public PartialViewResult ToolsTop()
        {

            return PartialView();
        }
    }
}

MovieProject/Views/Shared/Category.cshtml
@model List<Models.EF.Category>
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Thể loại <b class="caret"></b></a>
    <ul class="dropdown-menu multi-column columns-3">
        <li>
            <div class="col-sm-4">
                <ul class="multi-column-dropdown">
                    @foreach (var item in Model)
                    {
                        <li><a href="/theloai/@item.CategoryID">@item.NameCategory</a></li>
                       
                    }
                   
                </ul>
            </div>
            <div class="clearfix"></div>
        </li>
    </ul>
</li>

MovieProject/Views/Shared/Country.cshtml
@model List<Models.EF.Country>
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Quốc Gia<b class="caret"></b></a>
    <ul class="dropdown-menu multi-column columns-3">
        <li>
            <div class="col-sm-4">
                <ul class="multi-column-dropdown">
                  @foreach (var qg in Model)
                  {
                    <li><a href="/country/@qg.CountryID">@qg.Name</a></li>
                  }
                </ul>
            </div>
            <div class="clearfix"></div>
        </li>
    </ul>
</li>

MovieProject/Views/Shared/MenuBottom.cshtml
@model List<Models.EF.Category>

<div class="col-md-7 w3ls_footer_grid1_right">
    <ul>
        @foreach (var mn in Model)
        {
            <li>
                <a href="#">@mn.NameCategory</a>
            </li>
        }
        <li>
            <a href="/contact/">Liên hệ</a>
        </li>

    </ul>
</div>

MovieProject/Views/Shared/MenuMain.cshtml
<div class="movies_nav">
    <div class="container">
        <nav class="navbar navbar-default">
            <div class="navbar-header navbar-left">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
                <nav>
                    <ul class="nav navbar-nav">
                        <li ><a href="/Home/Index">Trang Chủ</a></li>
                       @{ Html.RenderAction("Category", "M");}
                        <li><a href="/new/">Tin tức</a></li>
                       @{ Html.RenderAction("Country","M");}

                        <li><a href="/about/">Giới Thiệu</a></li>
                        <li><a href="/contact/">Liên Hệ</a></li>
                    </ul>
                </nav>
            </div>
        </nav>
    </div>
</div>

MovieProject/Views/Shared/ToolsTop.cshtml
<div class="w3l_sign_in_register">
    @{ 
        var session = (MovieProject.Common.UserLogin)Session[MovieProject.Common.CommonContants.USER_SESSION];
    }
    @if (session == null)
    {
        <ul>
            <li><i class="fa fa-phone" aria-hidden="true"></i> +84 392 258 8899</li>
            <li><a href="/dangnhap/">Đăng nhập</a></li>
            <li><a href="/dangky/">Đăng ký</a></li>
        </ul>
    }
    else
    {
        <i><strong>Xin Chào:@session.UserName</strong></i>
        <i>@Html.ActionLink("Đăng xuất","Logout","UserT")</i>
    }

</div>

<div class="clearfix"> </div>

MovieProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>OneMovie Website xem phim hoàn toàn miễn phí</title><!-- for-mobile-apps -->
    <!-- for-mobile-apps -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="One Movies Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript">
        addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
               function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- //for-mobile-apps -->
    <link href="~/assets/web/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/assets/web/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <link rel="stylesheet" href="~/assets/web/css/contactstyle.css" type="text/css" media="all" />
    <link rel="stylesheet" href="~/assets/web/css/faqstyle.css" type="text/css" media="all" />
    <link href="~/assets/web/css/single.css" rel='stylesheet' type='text/css' />
    <link href="~/assets/web/css/medile.css" rel='stylesheet' type='text/css' />
    <!-- news-css -->
    <link rel="stylesheet" href="~/assets/web/news-css/news.css" type="text/css" media="all" />
    <!-- //news-css -->
    <!-- list-css -->
    <link rel="stylesheet" href="~/assets/web/list-css/list.css" type="text/css" media="all" />
    <!-- //list-css -->
    <!-- banner-slider -->
    <link href="~/assets/web/css/jquery.slidey.min.css" rel="stylesheet">
    <!-- //banner-slider -->
    <!-- pop-up -->
    <link href="~/assets/web/css/popuo-box.css" rel="stylesheet" type="text/css" media="all" />
    <!-- //pop-up -->
    <!-- font-awesome icons -->
    <link rel="stylesheet" href="~/assets/web/css/font-awesome.min.css" />
    <!-- //font-awesome icons -->
    <!-- js -->
    <script type="text/javascript" src="~/assets/web/js/jquery-2.1.4.min.js"></script>
    <!--Live chat-->
    <link href="~/assets/web/css/livechat.css" rel="stylesheet" />
    <script src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.9"></script>
    <script>jQuery(document).ready(function ($) { function detectmob() { if (navigator.userAgent.match(/Android/i) || navigator.userAgent.match(/webOS/i) || navigator.userAgent.match(/iPhone/i) || navigator.userAgent.match(/iPad/i) || navigator.userAgent.match(/iPod/i) || navigator.userAgent.match(/BlackBerry/i) || navigator.userAgent.match(/Windows Phone/i)) { return true; } else { return false; } } var t = { delay: 125, overlay: $(".fb-overlay"), widget: $(".fb-widget"), button: $(".fb-button") }; setTimeout(function () { $("div.fb-livechat").fadeIn() }, 8 * t.delay); if (!detectmob()) { $(".ctrlq").on("click", function (e) { e.preventDefault(), t.overlay.is(":visible") ? (t.overlay.fadeOut(t.delay), t.widget.stop().animate({ bottom: 0, opacity: 0 }, 2 * t.delay, function () { $(this).hide("slow"), t.button.show() })) : t.button.fadeOut("medium", function () { t.widget.stop().show().animate({ bottom: "30px", opacity: 1 }, 2 * t.delay), t.overlay.fadeIn(t.delay) }) }) } });</script>
    <!-- //js -->
    <!--Dark Mode-->
    <script src="~/assets/web/js/JavaScript.js"></script>
    <!-- banner-bottom-plugin -->
    <link href="~/assets/web/css/owl.carousel.css" rel="stylesheet" type="text/css" media="all">
    <script src="~/assets/web/js/owl.carousel.js"></script>
    <script>
        $(document).ready(function () {
            $("#owl-demo").owlCarousel({

                autoPlay: 3000, //Set AutoPlay to 3 seconds

                items: 5,
                itemsDesktop: [640, 4],
                itemsDesktopSmall: [414, 3]

            });

        });
    </script>
    <!-- //banner-bottom-plugin -->
    <link href='//fonts.googleapis.com/css?family=Roboto+Condensed:400,700italic,700,400italic,300italic,300' rel='stylesheet' type='text/css'>
    <!-- start-smoth-scrolling -->
    <script type="text/javascript" src="~/assets/web/js/move-top.js"></script>
    <script type="text/javascript" src="~/assets/web/js/easing.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $(".scroll").click(function (event) {
                event.preventDefault();
                $('html,body').animate({ scrollTop: $(this.hash).offset().top }, 1000);
            });
        });
    </script>
    <!-- start-smoth-scrolling -->
    <!--Facebook Comment-->
    <meta property="fb:app_id" content="551366955654782" />
    <meta property="fb:admins" content="100005868942037" />
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v5.0&appId=551366955654782&autoLogAppEvents=1"></script>

</head>

<body>

    <!-- header -->
    <div class="header">
        <div class="container">
            <div class="w3layouts_logo">
                <!-- logo -->
                <a href="/Home/Index"><h1>One<span>Movies</span></h1></a>
            </div>
            <div class="w3_search">
                <form name="timkiem" action="/Home/Search">
                    <input type="text" name="searchKey" placeholder="Nhập tên phim">
                    <input type="submit" name="submit" value="Tìm kiếm">
                </form>
            </div>
         
            @{ Html.RenderAction("ToolsTop", "UserT");}
        </div>
    </div>
    <!-- //header -->
    <!-- bootstrap-pop-up -->
    <script>
        $('.toggle').click(function () {
            // Switches the Icon
            $(this).children('i').toggleClass('fa-pencil');
            // Switches the forms
            $('.form').animate({
                height: "toggle",
                'padding-top': 'toggle',
                'padding-bottom': 'toggle',
                opacity: "toggle"
            }, "slow");
        });
    </script>
    <!-- //bootstrap-pop-up -->
    <!-- nav -->
    @RenderPage("MenuMain.cshtml")


    <!-- //nav -->
    <!-- banner -->
    @RenderSection("slide", required: false)


    <!-- //banner -->
    <!--facebook live-->
    <div class="fb-livechat"> <div class="ctrlq fb-overlay"></div><div class="fb-widget"> <div class="ctrlq fb-close"></div><div class="fb-page" data-href="https://www.facebook.com/OneMoviesDemo" data-tabs="messages" data-width="360" data-height="400" data-small-header="true" data-hide-cover="true" data-show-facepile="false"> </div><div class="fb-credit"> <a href="https://chanhtuoi.com" target="_blank">Powered by Chanhtuoi</a> </div><div id="fb-root"></div></div><a href="https://m.me/OneMoviesDemo" title="Gửi tin nhắn cho chúng tôi qua Facebook" class="ctrlq fb-button"> <div class="bubble">1</div><div class="bubble-msg">Bạn cần hỗ trợ?</div></a></div>

    <div class="general_social_icons">
        <nav class="social">
            <ul>
                <li class="w3_twitter"><a href="#">Twitter <i class="fa fa-twitter"></i></a></li>
                <li class="w3_facebook"><a href="https://www.Facebook.com/sonkenneth98/">Facebook <i class="fa fa-facebook"></i></a></li>
                <li class="w3_g_plus"><a href="#">Google+ <i class="fa fa-google-plus"></i></a></li>
            </ul>
        </nav>
    </div>

    @RenderBody()
    <!-- footer -->
    <div class="footer">
        <div class="container">
            <div class="w3ls_footer_grid">
                <div class="col-md-6 w3ls_footer_grid_left">
                    <div class="w3ls_footer_grid_left1">
                        <h2>Đăng Ký Nhận Thông Báo</h2>
                        <div class="w3ls_footer_grid_left1_pos">
                            <form action="#" method="post">
                                <input type="email" name="email" placeholder="Nhập Email của bạn" required="">
                                <input type="submit" value="Đăng Ký">
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 w3ls_footer_grid_right">
                    <a href="~/assets/web/index.html"><h2>One<span>Movies</span></h2></a>
                </div>
                <div class="clearfix"> </div>
            </div>
            <div class="col-md-5 w3ls_footer_grid1_left">
                <p>&copy; 2019 One Movies. All rights reserved </p>
            </div>

            @{Html.RenderAction("MenuBottom", "M");}
            <div class="clearfix"> </div>
        </div>
    </div>
    <!-- //footer -->
    <!-- Bootstrap Core JavaScript -->
    <script src="~/assets/web/js/bootstrap.min.js"></script>
    <script>
        $(document).ready(function () {
            $(".dropdown").hover(
                function () {
                    $('.dropdown-menu', this).stop(true, true).slideDown("fast");
                    $(this).toggleClass('open');
                },
                function () {
                    $('.dropdown-menu', this).stop(true, true).slideUp("fast");
                    $(this).toggleClass('open');
                }
            );
        });
    </script>
    <!-- //Bootstrap Core JavaScript -->
    <!-- here stars scrolling icon -->
    <script type="text/javascript">
        $(document).ready(function () {
			/*
				var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear'
				};
			*/

            $().UItoTop({ easingType: 'easeOutQuart' });

        });
    </script>

    @RenderSection("jsFooter", required: false)
    <!-- //here ends scrolling icon -->
    <!--Live Chat FaceBook-->


</body>
</html>

MovieProject/Views/Shared/_LoginModal.cshtml
@section jsFooter{
    <script src="~/assets/web/js/controller/registerController.js"></script>
    }
<div class="modal video-modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModal">
   
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                Đăng nhập
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <section>
                <div class="modal-body">
                    <div class="w3_login_module">
                        <div class="module form-module">
                            <div class="toggle">
                                <i class="fa fa-times fa-pencil"></i>
                                <div class="tooltip">Đăng Ký</div>
                            </div>
                            <div class="form">
                                <h3>Đăng nhập tài khoản</h3>
                                <form action="#" method="post">
                                    <input type="text" name="Username" placeholder="Tài Khoản" required="">
                                    <input type="password" name="Password" placeholder="Mật Khẩu" required="">
                                    <input type="submit" value="Đăng Nhập">
                                </form>
                            </div>
                            <div class="form">
                                <h3>Tạo tài khoản</h3>
                                <form action="#" method="post">
                                    @*<input type="text" id="txtName" placeholder="Tên bạn" required="">
                                    <input type="text" id="txtUserName" placeholder="Tài khoản" required="">
                                    <input type="password" name="txtPassword" placeholder="Mật Khẩu" required="">
                                    <input id="btnSend" type="submit" value="Đăng Ký">*@
                                </form>
                            </div>
                            <div class="cta"><a href="#">Quên mật khẩu ?</a></div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>